### PR TITLE
The connection will never be torn down even if the DHCP lease expires

### LINKED ISSUE #32: connection timed out on network device nbd0
Hi,
After a discussion with the support staff, it has been determined that arch linux, the latest packages, has problems with the type of network devices y'all are using. I'm getting lots of errors about connection timed out and unable to read block device when booting my server, causing it not to be able to boot. I'm trying to figure out a work-around for this, as currently I'd rather not switch from arch linux, if only because I have lots of data on that server that I really don't want to have to move.
Any help?
-Michael.

### PR DESCRIPTION
**Pull request by QuentinPerez**
closes #32

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Works for me :+1:

**Comment by moul** [comment]
LGTM

**Comment by moul** [comment]
@QuentinPerez what about porting this patch to every other systemd-based distros ?

**Comment by lilmike** [comment]
Does this make systemd able to be upgraded? If so, how do we apply it to an already-running server.
-Michael.

**Comment by mikkeloscar** [comment]
@lilmike you just add the lines from this commit to `/etc/systemd/network/eth0.network` before upgrading systemd.

If you already upgraded to 230, then you can use the method described [here](https://github.com/scaleway/image-archlinux/issues/25#issuecomment-161789610) to chroot into your volume and fix the issue (that's what I did).

**Pull request merged**
